### ISSUE TITLE
Data Persistence SQL Lite

### ISSUE THREAD

**Issue by DasProffi** [helpwave/mobile-app#126]
PatientDataService should use SQL Lite to store data permanently instead of a .json file

**Comment by DasProffi** [comment]
This would require two additional tables for allergies and medications, do we still want to use a sql persistence for patientData?

**Comment by MaxSchaefer** [comment]
Yes, why not? What's the problem with two additional tables?

**Comment by DasProffi** [comment]
The overhead of maintaining three tables for one data class and then putting three objects in one class.

If we have three tables, should we also use PatientData, AllergyEntry, MediactionEntry as separate classes?
