### ISSUE TITLE
helpwave tasks app setup

### ISSUE THREAD

**Issue by DasProffi** [helpwave/mobile-app#141]
Tracking Issue for the initialization of the helpwave kanban app:
- [x] #142
- [x] #143
- [x] #144
- [x] #145
- [x] #155
- [x] #169

**Comment by florian-sabonchi** [comment]
Close in #158

**Comment by DasProffi** [comment]
Only close this, when all subtasks are closed

**Comment by DasProffi** [comment]
All subtasks closed
