### ISSUE TITLE
Change Naming Convention of Pages

### ISSUE THREAD

**Issue by DasProffi** [helpwave/mobile-app#217]
`Page` is an internal class used by the flutter router, therefore we should rename all "pages" to the unused name `Screen`

e.g. `HomePage` will now be called `HomeScreen`

**Every `Screen` must contain a root scaffold widget**

**Comment by use-to** [comment]
@DasProffi is this issues also responsable for the scaffold refactoring?
Every `Screen` must contain a root scaffold widget. This state should be ensured.
Also maybe create a reusable component (draft only) for those main screens (appbar, drawer, etc. pp.)

**Comment by use-to** [comment]
![image](https://user-images.githubusercontent.com/13922835/222482612-e6f31d00-1f88-41bb-9f4d-5a049aeb8732.png)

**Comment by DasProffi** [comment]
> @DasProffi is this issues also responsable for the scaffold refactoring?

No, this issue only deals with changing the naming convention

**Comment by DasProffi** [comment]
OrganizationPage is the only one violating the "A `Screen` always has to have a `Scaffold` rule"

**Comment by use-to** [comment]
> > @DasProffi is this issues also responsable for the scaffold refactoring?
> 
> No, this issue only deals with changing the naming convention

Can you (as the maintainer) reference the right issue for that?

**Comment by DasProffi** [comment]
> Can you (as the maintainer) reference the right issue for that?
> 
> We also have to clean up some "old" components and screens. (e.g. delete authentication screens)

Yes, that is scheduled after finalizing the new design and agreeing upon it
