### ISSUE TITLE
New screen structure 

### ISSUE THREAD

**Issue by DasProffi** [helpwave/mobile-app#221]
**Wait for #217 to finish**

As mentioned in #217 change all screens to return a Scaffold at the root of the return.

Delete all screens in helpwave tasks that are listed below as in #225:
- Register
- Login
- Organization*
- Home

**Comment by use-to** [comment]
![image](https://user-images.githubusercontent.com/13922835/223275572-e8dfef46-edfc-4d7d-bb59-41331bdb6c80.png)
