### ISSUE TITLE
Loading Future builder

### ISSUE THREAD

**Issue by DasProffi** [helpwave/mobile-app#249]
Future builder with onData, loading and error widgets

**Comment by use-to** [comment]
I already talked about a helpwave (icon) loading spinner with @JannikWibker.

**Comment by DasProffi** [comment]
> I already talked about a helpwave (icon) loading spinner with @JannikWibker.

This is a general pupose widget to simplify the usage of a FutureBuilder by distinguishing the three important states of a Future loading, error and loading completed (then)

Design related things would require a new issue

**Comment by use-to** [comment]
> > I already talked about a helpwave (icon) loading spinner with @JannikWibker.
> 
> This is a general pupose widget to simplify the usage of a FutureBuilder by distinguishing the three important states of a Future loading, error and loading completed (then)
> 
> Design related things would require a new issue

Yeah obviously. I'm a little bit concerned that this widget does not provide the desired effect. Why should'nt I just use the `FutureBuilder`? Only to reduce the amount of those `if`-statements?

**Comment by DasProffi** [comment]
> Yeah obviously. I'm a little bit concerned that this widget does not provide the desired effect. Why should'nt I just use the `FutureBuilder`? Only to reduce the amount of those `if`-statements?

No, to also provide a standardized Error/Loading Widget without any code additons
