### ISSUE TITLE
Implement `PillLabelColumn` component

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/mobile-app#268]
Same as on web. This component indicates the status of all tasks of a patient.

![Image](https://user-images.githubusercontent.com/40192999/266453758-82834177-9bbe-40cd-bb65-399889819d14.png)

**Comment by DasProffi** [comment]
Already exists, see:
https://github.com/helpwave/mobile-app/blob/main/apps/tasks/lib/components/task_status_pill_box.dart
