### ISSUE TITLE
Implement `PatientCard` component

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/mobile-app#269]
The data will be passed down to that component. See the data classes from https://github.com/helpwave/mobile-app/pull/275#pullrequestreview-1623271414.

![Image](https://user-images.githubusercontent.com/40192999/266454089-350b37df-64e1-45f8-883f-ca40bb1ac5c3.svg)

**Comment by DasProffi** [comment]
Look at the old bed card, some parts might be reusable
