### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/mobile-app#276]
This is a tracking issue for adopting our OIDC provider auth.helpwave.de in the same way as already done in web. Including our Fake-Token strategy. The whole Fake-Token and redirect process should be as generic as possible with a concrete implementation of for example an auth guard per app that delegates the most logic to a lib.

Some facts:
- The app should hold a pre-defined Fake-Token
- In development, the Fake-Token should be used for bypassing the OIDC provider in conjunction with our API
- The bypassing should work by either ...
  - ... preventing the OAuth redirect and using the Fake-Token directly
  - ... redirecting the user via the Fake-Token and do a specific check for a Fake-Token
  - _See https://github.com/helpwave/web/blob/main/tasks/utils/oauth.ts#L101_
- If the token is invalid/outdated, restart the Authentication process
- Our OIDC provider provides a default OIDC flow
  - _See https://github.com/helpwave/web/blob/main/tasks/utils/oauth.ts_
- _Refresh tokens tbd_

```[tasklist]
### Tasks
- [ ] https://github.com/helpwave/mobile-app/issues/277
- [ ] Implementing Fake-Token logic
```

**Comment by DasProffi** [comment]
implemented
