### ISSUE TITLE
Evaluate Bloc lib and design pattern

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/mobile-app#384]
### Describe the chore

We need to evaluate a design pattern that structuralizes our mobile-app code-base. What about Bloc? It's got already mentioned a lot of times on the #MSHACK23.

- https://bloclibrary.dev
- https://www.flutterclutter.dev/flutter/basics/what-is-the-bloc-pattern/2021/2084/

**Comment by DasProffi** [comment]
We do not use the bloc pattern. Instead, we use the [provider package](https://pub.dev/packages/provider).

This pattern uses a Provider that provides a state usable by all children of that provider with a Consumer. The states are implemented as their own class called States, which allows to notify the Consumers to update all children with custom logic in between.
