### ISSUE TITLE
Date Time Selection

### ISSUE THREAD

**Issue by DasProffi** [helpwave/mobile-app#387]
### Describe the feature

A Text which displays the date with minute, hours, day, month and maybe years and onClick  open a dialog to set the date and time.

### Why is this feature needed?

To display and change `DateTime`s

### Additional context

From #359

**Comment by MaxSchaefer** [comment]
@DasProffi not ready?

**Comment by DasProffi** [comment]
> @DasProffi not ready? 

We had no clearly defined date format then, but in some PR I improvised one, making this ready
