### ISSUE TITLE
Overflow on task TaskBottomSheet

### ISSUE THREAD

**Issue by florian-sabonchi** [helpwave/mobile-app#401]
### Describe the bug

On the Google nexus 4 we have an overflow on the TaskBottomSheet 

### Describe how to produce the bug

Open the TaskBottomSheet on a Google nexus 4 

### Additional context

![grafik](https://github.com/helpwave/mobile-app/assets/54689374/e13d97d7-fca9-4554-904f-955617a6b79c)

**Comment by DasProffi** [comment]
How do we want to resolve this? I would suggest making the entire sheet scrollable except the title row with the patient, which should stay static. @florian-sabonchi do you agree or have a different idea?

**Comment by florian-sabonchi** [comment]
> How do we want to resolve this? I would suggest making the entire sheet scrollable except the title row with the patient, which should stay static. @florian-sabonchi do you agree or have a different idea?

Yes, sounds good to me 👍🏿
