### ISSUE TITLE
Refactor Consumer and Provider Usage

### ISSUE THREAD

**Issue by florian-sabonchi** [helpwave/mobile-app#414]
### Describe the feature

According to the official documentation of flutter, the consumer Widget shouldn't be returned directly

https://docs.flutter.dev/data-and-backend/state-mgmt/simple#changenotifierprovider

### Why is this feature needed?

To improve code quality

**Comment by DasProffi** [comment]
@florian-sabonchi To clarify, the purpose of this issue is to only wrap the component that needs the consumer in the consumer, correct?

If so please update the title to reflect that otherwise be more detailed in the description how this should be implemented

**Comment by florian-sabonchi** [comment]
> @florian-sabonchi To clarify, the purpose of this issue is to only wrap the component that needs the consumer in the consumer, correct?
> 
> If so please update the title to reflect that otherwise be more detailed in the description how this should be implemented

Yes I mean only wrap nessary components

**Comment by MaxSchaefer** [comment]
@florian-sabonchi if this is still an issue, can you work on this?
