### ISSUE TITLE
Room-Bed Selector

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/mobile-app#416]
### Describe the bug

![Bildschirmfoto 2023-10-23 um 11 20 14 PM](https://github.com/helpwave/mobile-app/assets/40192999/85ad392e-9f44-48c2-959a-291c05ae468f)

The Room-Bed selector is invisible. Also, the text color during a selection is dimmed.

### Describe how to produce the bug

Open a patient card

**Comment by DasProffi** [comment]
The invisibility is there because no bed is provided, and we have no hint text. So both are aspects to be considered for implementation

**Comment by DasProffi** [comment]
The lack of a provided bed is caused by the `GetPatient` not returning an optional bed and room. A issue for this in the backend is already open: https://github.com/helpwave/services/issues/481
