### ISSUE TITLE
Edit-Pen

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/mobile-app#417]
### Describe the chore

![Bildschirmfoto 2023-10-23 um 11 22 06 PM](https://github.com/helpwave/mobile-app/assets/40192999/d314957e-3bd4-49f2-b284-c171509b759e)

The user should be able to edit a patient or task name on a click.

- Patient card
- Task card

**Comment by DasProffi** [comment]
#415 covers this for the task bottom sheet

**Comment by DasProffi** [comment]
And regarding the icon, I thought we wanted to use color coding for this by making the text purple?
