### ISSUE TITLE
Task status on patient card

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/mobile-app#418]
### Describe the bug

![Bildschirmfoto 2023-10-23 um 11 24 47 PM](https://github.com/helpwave/mobile-app/assets/40192999/5b8fca04-340e-4ac4-9a73-0dd23a7a4b39)

The patient card shows 0/0/0 tasks

### Describe how to produce the bug

Open the patient list

**Comment by DasProffi** [comment]
The backend request get `GetPatientListRequest` does not provide this information, the backend issue will be linked here

**Comment by MaxSchaefer** [comment]
Ready
