### ISSUE TITLE
"Create"-Button for task and patient

### ISSUE THREAD

**Issue by DasProffi** [helpwave/mobile-app#461]
### Describe the feature

When creating a task in the TaskBottomSheet, implement an add button or save on closing the TaskBottomSheet

### Why is this feature needed?

To save and update tasks

**Comment by MaxSchaefer** [comment]
@DasProffi just a "Create"-Button should be enough. We want consistent updates.

**Comment by DasProffi** [comment]
> @DasProffi just a "Create"-Button should be enough. We want consistent updates.

I agree, but closing the dialogue would delete all changes made. But for now a simple button is sufficient

**Comment by DasProffi** [comment]
Blocked by #482
