### ISSUE TITLE
fix light theme

### ISSUE THREAD

**Issue by florian-sabonchi** [helpwave/mobile-app#462]
### Describe the bug

seems like that we have an issue with the white theme looks at the screenshots

### Describe how to produce the bug

change to white theme

### Additional context

![image](https://github.com/helpwave/mobile-app/assets/54689374/8a3c1a11-df69-4b7d-9c80-5b656b76e7e4)

**Comment by MaxSchaefer** [comment]
@florian-sabonchi could you work on this?

**Comment by MaxSchaefer** [comment]
Also please default to the white theme
