### ISSUE TITLE
Exit textarea

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/mobile-app#468]
### Describe the bug

Right now there is no way to exit a textarea (see screenshot). An outside touch/click does not defocuses the input.

### Describe how to produce the bug

Open a task, click into the description (textarea).

### Additional context

![simulator_screenshot_B5843235-2288-45E5-87FD-ABF022750503](https://github.com/helpwave/mobile-app/assets/40192999/06b22fa2-3376-478e-afe8-13f027ac52e4)

**Comment by florian-sabonchi** [comment]
Hello can't reproduce please re open if necessary
