### ISSUE TITLE
EmergencyChatPage

### ISSUE THREAD

**Issue by use-to** [helpwave/mobile-app#53]

**Comment by DasProffi** [comment]
What is the purpose of the EmergencyDetailsChatViewPage and what design should be used?
And when should it be displayed

**Comment by use-to** [comment]
Look at this picture: https://signal.org/blog/images/message-requests-header.jpg
Just a very basic chat view. You should be able to text a message to the emergency room.

**Comment by use-to** [comment]
Later on (not tracked by this issue atm), we could add voice messages and predefined quick chat buttons (like those "BLOCK"/ "DELETE"-buttons)
