### ISSUE TITLE
Light-theme for EmergencyRoomBottomSheet

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/mobile-app#57]
I have tested it on iOS, there as in the screenshot the sheet is in dark theme while I have the setting on light theme. If this is only the case on iOS, please let me know.

![Simulator Screen Shot - iPhone 14 Pro - 2022-11-06 at 12 00 11](https://user-images.githubusercontent.com/40192999/200166892-c6ad9edf-1580-41eb-9145-777e82e57a14.png)

**Comment by DasProffi** [comment]
Wait until new design is finished

**Comment by DasProffi** [comment]
helpwave app was removed in https://github.com/helpwave/mobile-app/pull/273/
