### ISSUE TITLE
Text of `notifyCancel`-Button overflows

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/mobile-app#58]
![Simulator Screen Shot - iPhone 14 Pro - 2022-11-06 at 12 09 08](https://user-images.githubusercontent.com/40192999/200167226-a248ce28-0e2a-454d-9493-b60b612de959.png)

**Comment by DasProffi** [comment]
How do want to approach this?
- shorten the Text to "Zurücknehmen" 
- increase the button height to allow a two line Text
- Something completly diffrent like a Status report with a cancel button at the end
![Capture](https://user-images.githubusercontent.com/67233923/211206008-8dea405b-7366-4497-ba39-3b3ea1776906.JPG)
- or maybe something else

**Comment by MaxSchaefer** [comment]
We should shorten the text to "Zurücknehmen"/"Cancel". I'm pretty sure we'll be expanding the feature in the future.
