### ISSUE TITLE
emergency departments list

### ISSUE THREAD

**Issue by use-to** [helpwave/mobile-app#6]
This widget should serve a emergency departments listview.
Start with a hardcoded list of emergency department objects.

**Comment by DasProffi** [comment]
"Widget" means reusable widget in this case or should the list view be embedded in a page (Scaffold widget)?

**Comment by MaxSchaefer** [comment]
I think the purpose of this issue is a list of emergency rooms. The list itself should be on a page. The entries inside this list should be a reusable component.
