### ISSUE TITLE
Patient data

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/mobile-app#72]
This tracking issue tracks the progress of a form element that gathers patient data. Patient data should only be persisted on the client for the time being.

Something similar is already implemented in some smartphone operating systems. It's nice to have our own forms and build more features on-top of it. Data that's already available to our app via the os should be imported later on.

### Tracked issues
- [x] #73
- [x] #74
- [x] #75
- [x] #76
- [x] #77
- [x] #86 
- [x] #88

**Comment by DasProffi** [comment]
Do we also want to add an issue for patient data storage on the device?
And an issue for the data class PatientData?

**Comment by MaxSchaefer** [comment]
> Do we also want to add an issue for patient data storage on the device?
> And an issue for the data class PatientData?

Could you provide more infos in this #88 issue?

**Comment by DasProffi** [comment]
This issue can be closed, or are there more tasks for persistent patient data that we want to add later?

**Comment by MaxSchaefer** [comment]
I will leave this open until the medical-review with @aegis301.

**Comment by aegis301** [comment]
Thanks for tagging, on it!

**Comment by MaxSchaefer** [comment]
As discussed on Slack, we do the medical-review asynchronously here on GitHub.

@aegis301 you can open the app via [BrowserStack](https://app-live.browserstack.com/dashboard#os=android&os_version=13.0&device=Google+Pixel+7+Pro&app_hashed_id=146e5e9fe96b897a0c070549661475648184da6c&start=true). The build is from [today (5fc90b1)](https://github.com/helpwave/mobile-app/commit/5fc90b1c82cddba6dd049125928a0166366ec339). Please take a look at the Patient data feature (Einstellungen > Notfallpass). You can leave your review here in the issue.

**Comment by aegis301** [comment]
Hey guys, medical review done. Looking great so far! An interesting information for medical professionals is not only the kind of medication a patient uses, but also the dosage. But could be material for a future issue? This absolutely works so far.

**Comment by MaxSchaefer** [comment]
Thanks! At the latest, when the feature is integrated against a proper Medical API, we will also have a schema for the dose.
