### ISSUE TITLE
Basic patient data form

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/mobile-app#74]
For now, every attribute should be optional.

- Name
- Date of Birth
- Organ Donor
  - This should be a bool
- Weight
- Height
- Primary language

**Comment by Florian-Sabonchi** [comment]
Hi, Thanks for your issue. It would be useful if you could add some Mockups

**Comment by MaxSchaefer** [comment]
Right now there are no mocks. But we can get inspiration from Apples Healthpass https://support.apple.com/de-de/HT207021.

**Comment by use-to** [comment]
Is there an interface for importing patient data from apple and android?
Maybe we should face that next... @MaxSchaefer
