### ISSUE TITLE
Form element for blood types

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/mobile-app#75]
We need a dropdown selection for the blood types below. This input should also be integrated into our patient data form as an optional field.

The rhesus factor is the + or - at the end of the blood group. The last four options are only blood groups without the rhesus factor, in case this information is not available. In the background, the select should output a structure where the blood group and rhesus factor is seperate.

- Blood types
  - A+
  - A-
  - B+
  - B-
  - AB+
  - AB-
  - O+
  - O-
  - A
  - B
  - AB
  - O

**Comment by use-to** [comment]
We can split up the blood type into (blood group, rhesus factor).

**Comment by MaxSchaefer** [comment]
Nice, I just asked Christian for the nomenclature of the rhesus factor so that we can provide the correct options to the user.

**Comment by MaxSchaefer** [comment]
I've updated the issue for the rhesus factor. Thanks for the suggestion.

**Comment by DasProffi** [comment]
The + in A+ is the rhesus factor, isn't it? Therefore the upper table would only be A, B, AB, O.

**Comment by MaxSchaefer** [comment]
Oh, you're right. There are some other rhesus factor nomenclatures, but with ABO the +/- is rhesus factor.
I don't really know how common it is that you know your blood group but not your rhesus factor. Let's have one select with the upper options and handle the blood group and rhesus factor in the background. And just in case, I've added three more options (A, B, AB and O) without the rhesus factor.

**Comment by MaxSchaefer** [comment]
_fyi: I like the discussion, features like this should be peer-reviewed for medical correctness (medical-review?) with Christian when they are done._
