### ISSUE TITLE
Persist patient data on device

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/mobile-app#88]

**Comment by DasProffi** [comment]
We need to store the patient data on the users device in a file flutter porvides an interface for this [(see here)](https://docs.flutter.dev/cookbook/persistence/reading-writing-files), maybe we can also use another package to make parsing easy.

Additionally, it might be useful to have a data class PatientData which contains all relvant data (Name, Birthdate, medicationDosageMap, Allergies, etc with nullable fields)
