### ISSUE TITLE
Overlapping Inputs

### ISSUE THREAD

**Issue by florian-sabonchi** [helpwave/mobile-app#95]
As soon as an input is made there is an overlapping of the input files by the keyboard

![image](https://user-images.githubusercontent.com/54689374/210079333-f2601418-ee24-48e8-961c-4cabf3a66ec8.png)

**Comment by DasProffi** [comment]
Could you give further information. Should the Label of type/rhesus be not visible? Or is there a conflict with the inputs at the top border of the input button 2 or 3?

**Comment by DasProffi** [comment]
@florian-sabonchi correct me if I am wrong
Goal of this Issue is to align the Input-Fields with the keyboard in such a way that the focused input field is directly above the keyboard.

What do we do with the Input-fields Name and Language not align?

**Comment by DasProffi** [comment]
helpwave app was removed in https://github.com/helpwave/mobile-app/pull/273/
