### ISSUE TITLE
Empty medications should be avoided

### ISSUE THREAD

**Issue by florian-sabonchi** [helpwave/mobile-app#98]
https://user-images.githubusercontent.com/54689374/210105675-a1784745-49b7-4144-b3a3-a5cddea822f1.mp4

**Comment by DasProffi** [comment]
Original issue doesn't appear in main branch anymore, but better validation would be good
- [ ] Empty entries should be avoided (possible if all other options are already selected)
- [ ] Null results from list search should be caught/accepted and then ignored
- [ ] Add button shouldn't show if addAnyway is false and there are no other search options left
